package com.example.eventconfig.enums;

public enum EventCategory {
    OTHER, GEOFENCE, ELECTRICAL, MAINTENANCE, ENVIRONMENTAL, LIFEANDSAFETY,
    SHUTDOWN, HVAC, PLUMBING, PREDICTIVE, PREVENTIVE, ELECTRICITYLOSS,
    CHILLEDWATERLOSS, ENERGYLOSS, FIREALARM, FAULTYSENSOR;
}
